# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Browser Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import DownloadProgressEvent, DownloadWillBeginEvent

class BrowserRegistration:
    """Event registration interface for Browser domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "Browser"
        self._mode = mode  # 'register' or 'unregister'

    def downloadWillBegin(
        self,
        callback: Union[Callable[['DownloadWillBeginEvent', Optional[str]], None], Callable[['DownloadWillBeginEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for downloadWillBegin events.
        
        Fired when page is about to start a download.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Browser.downloadWillBegin", callback, once)
        else:  # unregister mode
            self._registry.unregister("Browser.downloadWillBegin", callback)

    def downloadProgress(
        self,
        callback: Union[Callable[['DownloadProgressEvent', Optional[str]], None], Callable[['DownloadProgressEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for downloadProgress events.
        
        Fired when download makes progress. Last call has |done| == true.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Browser.downloadProgress", callback, once)
        else:  # unregister mode
            self._registry.unregister("Browser.downloadProgress", callback)

