# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tethering Domain Commands"""

from typing import TypedDict

class BindParameters(TypedDict):
    port: "int"
    """Port number to bind."""





class UnbindParameters(TypedDict):
    port: "int"
    """Port number to unbind."""


