# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tethering Domain Events"""

from typing import TypedDict

"""Informs that port was successfully bound and got a specified connection id."""
class AcceptedEvent(TypedDict):
    port: "int"
    """Port number that was successfully bound."""
    connectionId: "str"
    """Connection id to be used."""
