# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tethering Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import AcceptedEvent

class TetheringRegistration:
    """Event registration interface for Tethering domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "Tethering"
        self._mode = mode  # 'register' or 'unregister'

    def accepted(
        self,
        callback: Union[Callable[['AcceptedEvent', Optional[str]], None], Callable[['AcceptedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for accepted events.
        
        Informs that port was successfully bound and got a specified connection id.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Tethering.accepted", callback, once)
        else:  # unregister mode
            self._registry.unregister("Tethering.accepted", callback)

