# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import (
    AttributionReportingReportSentEvent,
    AttributionReportingSourceRegisteredEvent,
    AttributionReportingTriggerRegisteredEvent,
    AttributionReportingVerboseDebugReportSentEvent,
    CacheStorageContentUpdatedEvent,
    CacheStorageListUpdatedEvent,
    IndexedDBContentUpdatedEvent,
    IndexedDBListUpdatedEvent,
    InterestGroupAccessedEvent,
    InterestGroupAuctionEventOccurredEvent,
    InterestGroupAuctionNetworkRequestCreatedEvent,
    SharedStorageAccessedEvent,
    SharedStorageWorkletOperationExecutionFinishedEvent,
    StorageBucketCreatedOrUpdatedEvent,
    StorageBucketDeletedEvent
)

class StorageRegistration:
    """Event registration interface for Storage domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "Storage"
        self._mode = mode  # 'register' or 'unregister'

    def cacheStorageContentUpdated(
        self,
        callback: Union[Callable[['CacheStorageContentUpdatedEvent', Optional[str]], None], Callable[['CacheStorageContentUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for cacheStorageContentUpdated events.
        
        A cache's contents have been modified.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.cacheStorageContentUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.cacheStorageContentUpdated", callback)

    def cacheStorageListUpdated(
        self,
        callback: Union[Callable[['CacheStorageListUpdatedEvent', Optional[str]], None], Callable[['CacheStorageListUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for cacheStorageListUpdated events.
        
        A cache has been added/deleted.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.cacheStorageListUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.cacheStorageListUpdated", callback)

    def indexedDBContentUpdated(
        self,
        callback: Union[Callable[['IndexedDBContentUpdatedEvent', Optional[str]], None], Callable[['IndexedDBContentUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for indexedDBContentUpdated events.
        
        The origin's IndexedDB object store has been modified.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.indexedDBContentUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.indexedDBContentUpdated", callback)

    def indexedDBListUpdated(
        self,
        callback: Union[Callable[['IndexedDBListUpdatedEvent', Optional[str]], None], Callable[['IndexedDBListUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for indexedDBListUpdated events.
        
        The origin's IndexedDB database list has been modified.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.indexedDBListUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.indexedDBListUpdated", callback)

    def interestGroupAccessed(
        self,
        callback: Union[Callable[['InterestGroupAccessedEvent', Optional[str]], None], Callable[['InterestGroupAccessedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for interestGroupAccessed events.
        
        One of the interest groups was accessed. Note that these events are global
to all targets sharing an interest group store.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.interestGroupAccessed", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.interestGroupAccessed", callback)

    def interestGroupAuctionEventOccurred(
        self,
        callback: Union[Callable[['InterestGroupAuctionEventOccurredEvent', Optional[str]], None], Callable[['InterestGroupAuctionEventOccurredEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for interestGroupAuctionEventOccurred events.
        
        An auction involving interest groups is taking place. These events are
target-specific.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.interestGroupAuctionEventOccurred", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.interestGroupAuctionEventOccurred", callback)

    def interestGroupAuctionNetworkRequestCreated(
        self,
        callback: Union[Callable[['InterestGroupAuctionNetworkRequestCreatedEvent', Optional[str]], None], Callable[['InterestGroupAuctionNetworkRequestCreatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for interestGroupAuctionNetworkRequestCreated events.
        
        Specifies which auctions a particular network fetch may be related to, and
in what role. Note that it is not ordered with respect to
Network.requestWillBeSent (but will happen before loadingFinished
loadingFailed).
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.interestGroupAuctionNetworkRequestCreated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.interestGroupAuctionNetworkRequestCreated", callback)

    def sharedStorageAccessed(
        self,
        callback: Union[Callable[['SharedStorageAccessedEvent', Optional[str]], None], Callable[['SharedStorageAccessedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for sharedStorageAccessed events.
        
        Shared storage was accessed by the associated page.
The following parameters are included in all events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.sharedStorageAccessed", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.sharedStorageAccessed", callback)

    def sharedStorageWorkletOperationExecutionFinished(
        self,
        callback: Union[Callable[['SharedStorageWorkletOperationExecutionFinishedEvent', Optional[str]], None], Callable[['SharedStorageWorkletOperationExecutionFinishedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for sharedStorageWorkletOperationExecutionFinished events.
        
        A shared storage run or selectURL operation finished its execution.
The following parameters are included in all events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.sharedStorageWorkletOperationExecutionFinished", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.sharedStorageWorkletOperationExecutionFinished", callback)

    def storageBucketCreatedOrUpdated(
        self,
        callback: Union[Callable[['StorageBucketCreatedOrUpdatedEvent', Optional[str]], None], Callable[['StorageBucketCreatedOrUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for storageBucketCreatedOrUpdated events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.storageBucketCreatedOrUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.storageBucketCreatedOrUpdated", callback)

    def storageBucketDeleted(
        self,
        callback: Union[Callable[['StorageBucketDeletedEvent', Optional[str]], None], Callable[['StorageBucketDeletedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for storageBucketDeleted events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.storageBucketDeleted", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.storageBucketDeleted", callback)

    def attributionReportingSourceRegistered(
        self,
        callback: Union[Callable[['AttributionReportingSourceRegisteredEvent', Optional[str]], None], Callable[['AttributionReportingSourceRegisteredEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for attributionReportingSourceRegistered events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.attributionReportingSourceRegistered", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.attributionReportingSourceRegistered", callback)

    def attributionReportingTriggerRegistered(
        self,
        callback: Union[Callable[['AttributionReportingTriggerRegisteredEvent', Optional[str]], None], Callable[['AttributionReportingTriggerRegisteredEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for attributionReportingTriggerRegistered events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.attributionReportingTriggerRegistered", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.attributionReportingTriggerRegistered", callback)

    def attributionReportingReportSent(
        self,
        callback: Union[Callable[['AttributionReportingReportSentEvent', Optional[str]], None], Callable[['AttributionReportingReportSentEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for attributionReportingReportSent events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.attributionReportingReportSent", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.attributionReportingReportSent", callback)

    def attributionReportingVerboseDebugReportSent(
        self,
        callback: Union[Callable[['AttributionReportingVerboseDebugReportSentEvent', Optional[str]], None], Callable[['AttributionReportingVerboseDebugReportSentEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for attributionReportingVerboseDebugReportSent events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Storage.attributionReportingVerboseDebugReportSent", callback, once)
        else:  # unregister mode
            self._registry.unregister("Storage.attributionReportingVerboseDebugReportSent", callback)

