# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeadlessExperimental Domain Commands"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import ScreenshotParams

class BeginFrameParameters(TypedDict, total=False):
    frameTimeTicks: "float"
    """Timestamp of this BeginFrame in Renderer TimeTicks (milliseconds of uptime). If not set,
the current time will be used."""
    interval: "float"
    """The interval between BeginFrames that is reported to the compositor, in milliseconds.
Defaults to a 60 frames/second interval, i.e. about 16.666 milliseconds."""
    noDisplayUpdates: "bool"
    """Whether updates should not be committed and drawn onto the display. False by default. If
true, only side effects of the BeginFrame will be run, such as layout and animations, but
any visual updates may not be visible on the display or in screenshots."""
    screenshot: "ScreenshotParams"
    """If set, a screenshot of the frame will be captured and returned in the response. Otherwise,
no screenshot will be captured. Note that capturing a screenshot can fail, for example,
during renderer initialization. In such a case, no screenshot data will be returned."""


class BeginFrameReturns(TypedDict):
    hasDamage: "bool"
    """Whether the BeginFrame resulted in damage and, thus, a new frame was committed to the
display. Reported for diagnostic uses, may be removed in the future."""
    screenshotData: "str"
    """Base64-encoded image data of the screenshot, if one was requested and successfully taken. (Encoded as a base64 string when passed over JSON)"""
