# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeadlessExperimental Domain Types"""

from typing import TypedDict

class ScreenshotParams(TypedDict, total=False):
    """Encoding options for a screenshot."""

    format: "str"
    """Image compression format (defaults to png)."""
    quality: "int"
    """Compression quality from range [0..100] (jpeg and webp only)."""
    optimizeForSpeed: "bool"
    """Optimize image encoding for speed, not for resulting size (defaults to false)"""
