# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP BackgroundService Domain Commands"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import ServiceName

class StartObservingParameters(TypedDict):
    service: "ServiceName"





class StopObservingParameters(TypedDict):
    service: "ServiceName"





class SetRecordingParameters(TypedDict):
    shouldRecord: "bool"
    service: "ServiceName"





class ClearEventsParameters(TypedDict):
    service: "ServiceName"


