# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP BackgroundService Domain Events"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import BackgroundServiceEvent
    from .types import ServiceName

"""Called when the recording state for the service has been updated."""
class RecordingStateChangedEvent(TypedDict):
    isRecording: "bool"
    service: "ServiceName"



"""Called with all existing backgroundServiceEvents when enabled, and all new
events afterwards if enabled and recording."""
class BackgroundServiceEventReceivedEvent(TypedDict):
    backgroundServiceEvent: "BackgroundServiceEvent"
