# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP BackgroundService Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import BackgroundServiceEventReceivedEvent, RecordingStateChangedEvent

class BackgroundServiceRegistration:
    """Event registration interface for BackgroundService domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "BackgroundService"
        self._mode = mode  # 'register' or 'unregister'

    def recordingStateChanged(
        self,
        callback: Union[Callable[['RecordingStateChangedEvent', Optional[str]], None], Callable[['RecordingStateChangedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for recordingStateChanged events.
        
        Called when the recording state for the service has been updated.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("BackgroundService.recordingStateChanged", callback, once)
        else:  # unregister mode
            self._registry.unregister("BackgroundService.recordingStateChanged", callback)

    def backgroundServiceEventReceived(
        self,
        callback: Union[Callable[['BackgroundServiceEventReceivedEvent', Optional[str]], None], Callable[['BackgroundServiceEventReceivedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for backgroundServiceEventReceived events.
        
        Called with all existing backgroundServiceEvents when enabled, and all new
events afterwards if enabled and recording.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("BackgroundService.backgroundServiceEventReceived", callback, once)
        else:  # unregister mode
            self._registry.unregister("BackgroundService.backgroundServiceEventReceived", callback)

