# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Animation Domain Commands"""

from typing import List, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import RemoteObject

class GetCurrentTimeParameters(TypedDict):
    id: "str"
    """Id of animation."""


class GetCurrentTimeReturns(TypedDict):
    currentTime: "float"
    """Current time of the page."""



class GetPlaybackRateReturns(TypedDict):
    playbackRate: "float"
    """Playback rate for animations on page."""



class ReleaseAnimationsParameters(TypedDict):
    animations: "List[str]"
    """List of animation ids to seek."""





class ResolveAnimationParameters(TypedDict):
    animationId: "str"
    """Animation id."""


class ResolveAnimationReturns(TypedDict):
    remoteObject: "RemoteObject"
    """Corresponding remote object."""



class SeekAnimationsParameters(TypedDict):
    animations: "List[str]"
    """List of animation ids to seek."""
    currentTime: "float"
    """Set the current time of each animation."""





class SetPausedParameters(TypedDict):
    animations: "List[str]"
    """Animations to set the pause state of."""
    paused: "bool"
    """Paused state to set to."""





class SetPlaybackRateParameters(TypedDict):
    playbackRate: "float"
    """Playback rate for animations on page"""





class SetTimingParameters(TypedDict):
    animationId: "str"
    """Animation id."""
    duration: "float"
    """Duration of the animation."""
    delay: "float"
    """Delay of the animation."""


