# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Animation Domain Events"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Animation

"""Event for when an animation has been cancelled."""
class AnimationCanceledEvent(TypedDict):
    id: "str"
    """Id of the animation that was cancelled."""



"""Event for each animation that has been created."""
class AnimationCreatedEvent(TypedDict):
    id: "str"
    """Id of the animation that was created."""



"""Event for animation that has been started."""
class AnimationStartedEvent(TypedDict):
    animation: "Animation"
    """Animation that was started."""



"""Event for animation that has been updated."""
class AnimationUpdatedEvent(TypedDict):
    animation: "Animation"
    """Animation that was updated."""
