# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Preload Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import (
    PrefetchStatusUpdatedEvent,
    PreloadEnabledStateUpdatedEvent,
    PreloadingAttemptSourcesUpdatedEvent,
    PrerenderStatusUpdatedEvent,
    RuleSetRemovedEvent,
    RuleSetUpdatedEvent
)

class PreloadRegistration:
    """Event registration interface for Preload domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "Preload"
        self._mode = mode  # 'register' or 'unregister'

    def ruleSetUpdated(
        self,
        callback: Union[Callable[['RuleSetUpdatedEvent', Optional[str]], None], Callable[['RuleSetUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for ruleSetUpdated events.
        
        Upsert. Currently, it is only emitted when a rule set added.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.ruleSetUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.ruleSetUpdated", callback)

    def ruleSetRemoved(
        self,
        callback: Union[Callable[['RuleSetRemovedEvent', Optional[str]], None], Callable[['RuleSetRemovedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for ruleSetRemoved events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.ruleSetRemoved", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.ruleSetRemoved", callback)

    def preloadEnabledStateUpdated(
        self,
        callback: Union[Callable[['PreloadEnabledStateUpdatedEvent', Optional[str]], None], Callable[['PreloadEnabledStateUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for preloadEnabledStateUpdated events.
        
        Fired when a preload enabled state is updated.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.preloadEnabledStateUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.preloadEnabledStateUpdated", callback)

    def prefetchStatusUpdated(
        self,
        callback: Union[Callable[['PrefetchStatusUpdatedEvent', Optional[str]], None], Callable[['PrefetchStatusUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for prefetchStatusUpdated events.
        
        Fired when a prefetch attempt is updated.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.prefetchStatusUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.prefetchStatusUpdated", callback)

    def prerenderStatusUpdated(
        self,
        callback: Union[Callable[['PrerenderStatusUpdatedEvent', Optional[str]], None], Callable[['PrerenderStatusUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for prerenderStatusUpdated events.
        
        Fired when a prerender attempt is updated.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.prerenderStatusUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.prerenderStatusUpdated", callback)

    def preloadingAttemptSourcesUpdated(
        self,
        callback: Union[Callable[['PreloadingAttemptSourcesUpdatedEvent', Optional[str]], None], Callable[['PreloadingAttemptSourcesUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for preloadingAttemptSourcesUpdated events.
        
        Send a list of sources for all preloading attempts in a document.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Preload.preloadingAttemptSourcesUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("Preload.preloadingAttemptSourcesUpdated", callback)

