# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Performance Domain Events"""

from typing import List, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Metric

"""Current values of the metrics."""
class MetricsEvent(TypedDict):
    metrics: "List[Metric]"
    """Current values of the metrics."""
    title: "str"
    """Timestamp title."""
