# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Log Domain Commands"""

from typing import List, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import ViolationSetting

class StartViolationsReportParameters(TypedDict):
    config: "List[ViolationSetting]"
    """Configuration for violations."""


