# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Autofill Domain Commands"""

from typing import List, NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..page.types import FrameId
    from .types import Address
    from .types import CreditCard

class TriggerParameters(TypedDict):
    fieldId: "BackendNodeId"
    """Identifies a field that serves as an anchor for autofill."""
    frameId: "NotRequired[FrameId]"
    """Identifies the frame that field belongs to."""
    card: "NotRequired[CreditCard]"
    """Credit card information to fill out the form. Credit card data is not saved.  Mutually exclusive with `address`."""
    address: "NotRequired[Address]"
    """Address to fill out the form. Address data is not saved. Mutually exclusive with `card`."""





class SetAddressesParameters(TypedDict):
    addresses: "List[Address]"


