# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Autofill Domain Events"""

from typing import List, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import AddressUI
    from .types import FilledField

"""Emitted when an address form is filled."""
class AddressFormFilledEvent(TypedDict):
    filledFields: "List[FilledField]"
    """Information about the fields that were filled"""
    addressUi: "AddressUI"
    """An UI representation of the address used to fill the form.
Consists of a 2D array where each child represents an address/profile line."""
