# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP FileSystem Domain Types"""

from typing import List, NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..network.types import TimeSinceEpoch
    from ..storage.types import SerializedStorageKey

class File(TypedDict):
    name: "str"
    lastModified: "TimeSinceEpoch"
    """Timestamp"""
    size: "float"
    """Size in bytes"""
    type: "str"



class Directory(TypedDict):
    name: "str"
    nestedDirectories: "List[str]"
    nestedFiles: "List[File]"
    """Files that are directly nested under this directory."""



class BucketFileSystemLocator(TypedDict):
    storageKey: "SerializedStorageKey"
    """Storage key"""
    bucketName: "NotRequired[str]"
    """Bucket name. Not passing a `bucketName` will retrieve the default Bucket. (https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#storage_buckets)"""
    pathComponents: "List[str]"
    """Path to the directory using each path component as an array item."""
