# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ServiceWorker Domain Commands"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import RegistrationID

class DeliverPushMessageParameters(TypedDict):
    origin: "str"
    registrationId: "RegistrationID"
    data: "str"





class DispatchSyncEventParameters(TypedDict):
    origin: "str"
    registrationId: "RegistrationID"
    tag: "str"
    lastChance: "bool"





class DispatchPeriodicSyncEventParameters(TypedDict):
    origin: "str"
    registrationId: "RegistrationID"
    tag: "str"





class SetForceUpdateOnPageLoadParameters(TypedDict):
    forceUpdateOnPageLoad: "bool"





class SkipWaitingParameters(TypedDict):
    scopeURL: "str"





class StartWorkerParameters(TypedDict):
    scopeURL: "str"





class StopWorkerParameters(TypedDict):
    versionId: "str"





class UnregisterParameters(TypedDict):
    scopeURL: "str"





class UpdateRegistrationParameters(TypedDict):
    scopeURL: "str"


