# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Schema Domain Types"""

from typing import TypedDict

class Domain(TypedDict):
    """Description of the protocol domain."""

    name: "str"
    """Domain name."""
    version: "str"
    """Domain version."""
