# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOMStorage Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import DomStorageItemAddedEvent, DomStorageItemRemovedEvent, DomStorageItemUpdatedEvent, DomStorageItemsClearedEvent

class DOMStorageRegistration:
    """Event registration interface for DOMStorage domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "DOMStorage"
        self._mode = mode  # 'register' or 'unregister'

    def domStorageItemAdded(
        self,
        callback: Union[Callable[['DomStorageItemAddedEvent', Optional[str]], None], Callable[['DomStorageItemAddedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for domStorageItemAdded events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("DOMStorage.domStorageItemAdded", callback, once)
        else:  # unregister mode
            self._registry.unregister("DOMStorage.domStorageItemAdded", callback)

    def domStorageItemRemoved(
        self,
        callback: Union[Callable[['DomStorageItemRemovedEvent', Optional[str]], None], Callable[['DomStorageItemRemovedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for domStorageItemRemoved events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("DOMStorage.domStorageItemRemoved", callback, once)
        else:  # unregister mode
            self._registry.unregister("DOMStorage.domStorageItemRemoved", callback)

    def domStorageItemUpdated(
        self,
        callback: Union[Callable[['DomStorageItemUpdatedEvent', Optional[str]], None], Callable[['DomStorageItemUpdatedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for domStorageItemUpdated events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("DOMStorage.domStorageItemUpdated", callback, once)
        else:  # unregister mode
            self._registry.unregister("DOMStorage.domStorageItemUpdated", callback)

    def domStorageItemsCleared(
        self,
        callback: Union[Callable[['DomStorageItemsClearedEvent', Optional[str]], None], Callable[['DomStorageItemsClearedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for domStorageItemsCleared events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("DOMStorage.domStorageItemsCleared", callback, once)
        else:  # unregister mode
            self._registry.unregister("DOMStorage.domStorageItemsCleared", callback)

