# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Type-Safe Client"""

from . import console
from . import debugger
from . import heapprofiler
from . import profiler
from . import runtime
from . import schema
from . import accessibility
from . import animation
from . import audits
from . import autofill
from . import backgroundservice
from . import bluetoothemulation
from . import browser
from . import css
from . import cachestorage
from . import cast
from . import dom
from . import domdebugger
from . import domsnapshot
from . import domstorage
from . import deviceaccess
from . import deviceorientation
from . import emulation
from . import eventbreakpoints
from . import extensions
from . import fedcm
from . import fetch
from . import filesystem
from . import headlessexperimental
from . import io
from . import indexeddb
from . import input
from . import inspector
from . import layertree
from . import log
from . import media
from . import memory
from . import network
from . import overlay
from . import pwa
from . import page
from . import performance
from . import performancetimeline
from . import preload
from . import security
from . import serviceworker
from . import storage
from . import systeminfo
from . import target
from . import tethering
from . import tracing
from . import webaudio
from . import webauthn

from .library import CDPLibrary
from .registry import EventRegistry
from .registration_library import CDPRegistrationLibrary

__all__ = [
    "console",
    "debugger",
    "heapprofiler",
    "profiler",
    "runtime",
    "schema",
    "accessibility",
    "animation",
    "audits",
    "autofill",
    "backgroundservice",
    "bluetoothemulation",
    "browser",
    "css",
    "cachestorage",
    "cast",
    "dom",
    "domdebugger",
    "domsnapshot",
    "domstorage",
    "deviceaccess",
    "deviceorientation",
    "emulation",
    "eventbreakpoints",
    "extensions",
    "fedcm",
    "fetch",
    "filesystem",
    "headlessexperimental",
    "io",
    "indexeddb",
    "input",
    "inspector",
    "layertree",
    "log",
    "media",
    "memory",
    "network",
    "overlay",
    "pwa",
    "page",
    "performance",
    "performancetimeline",
    "preload",
    "security",
    "serviceworker",
    "storage",
    "systeminfo",
    "target",
    "tethering",
    "tracing",
    "webaudio",
    "webauthn",
    "CDPLibrary",
    "EventRegistry",
    "CDPRegistrationLibrary",
]
