# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Security Domain Commands"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import CertificateErrorAction

class SetIgnoreCertificateErrorsParameters(TypedDict):
    ignore: "bool"
    """If true, all certificate errors will be ignored."""





class HandleCertificateErrorParameters(TypedDict):
    eventId: "int"
    """The ID of the event."""
    action: "CertificateErrorAction"
    """The action to take on the certificate error."""





class SetOverrideCertificateErrorsParameters(TypedDict):
    override: "bool"
    """If true, certificate errors will be overridden."""


