# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Cast Domain Commands"""

from typing import TypedDict

class EnableParameters(TypedDict, total=False):
    presentationUrl: "str"





class SetSinkToUseParameters(TypedDict):
    sinkName: "str"





class StartDesktopMirroringParameters(TypedDict):
    sinkName: "str"





class StartTabMirroringParameters(TypedDict):
    sinkName: "str"





class StopCastingParameters(TypedDict):
    sinkName: "str"


