# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Cast Domain Events"""

from typing import List, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Sink

"""This is fired whenever the list of available sinks changes. A sink is a
device or a software surface that you can cast to."""
class SinksUpdatedEvent(TypedDict):
    sinks: "List[Sink]"



"""This is fired whenever the outstanding issue/error message changes.
|issueMessage| is empty if there is no issue."""
class IssueUpdatedEvent(TypedDict):
    issueMessage: "str"
