# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Profiler Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import ConsoleProfileFinishedEvent, ConsoleProfileStartedEvent, PreciseCoverageDeltaUpdateEvent

class ProfilerRegistration:
    """Event registration interface for Profiler domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "Profiler"
        self._mode = mode  # 'register' or 'unregister'

    def consoleProfileFinished(
        self,
        callback: Union[Callable[['ConsoleProfileFinishedEvent', Optional[str]], None], Callable[['ConsoleProfileFinishedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for consoleProfileFinished events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Profiler.consoleProfileFinished", callback, once)
        else:  # unregister mode
            self._registry.unregister("Profiler.consoleProfileFinished", callback)

    def consoleProfileStarted(
        self,
        callback: Union[Callable[['ConsoleProfileStartedEvent', Optional[str]], None], Callable[['ConsoleProfileStartedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for consoleProfileStarted events.
        
        Sent when new profile recording is started using console.profile() call.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Profiler.consoleProfileStarted", callback, once)
        else:  # unregister mode
            self._registry.unregister("Profiler.consoleProfileStarted", callback)

    def preciseCoverageDeltaUpdate(
        self,
        callback: Union[Callable[['PreciseCoverageDeltaUpdateEvent', Optional[str]], None], Callable[['PreciseCoverageDeltaUpdateEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for preciseCoverageDeltaUpdate events.
        
        Reports coverage delta since the last poll (either from an event like this, or from
`takePreciseCoverage` for the current isolate. May only be sent if precise code
coverage has been started. This event can be trigged by the embedder to, for example,
trigger collection of coverage data immediately at a certain point in time.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("Profiler.preciseCoverageDeltaUpdate", callback, once)
        else:  # unregister mode
            self._registry.unregister("Profiler.preciseCoverageDeltaUpdate", callback)

