# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP FedCm Domain Event Registration"""

from collections.abc import Awaitable
from typing import Callable, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import DialogClosedEvent, DialogShownEvent

class FedCmRegistration:
    """Event registration interface for FedCm domain."""

    def __init__(self, registry: 'EventRegistry', mode: str = 'register'):
        self._registry = registry
        self._domain = "FedCm"
        self._mode = mode  # 'register' or 'unregister'

    def dialogShown(
        self,
        callback: Union[Callable[['DialogShownEvent', Optional[str]], None], Callable[['DialogShownEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for dialogShown events.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("FedCm.dialogShown", callback, once)
        else:  # unregister mode
            self._registry.unregister("FedCm.dialogShown", callback)

    def dialogClosed(
        self,
        callback: Union[Callable[['DialogClosedEvent', Optional[str]], None], Callable[['DialogClosedEvent', Optional[str]], Awaitable[None]]],
        once: bool = False,
    ) -> None:
        """
        Register or unregister a callback for dialogClosed events.
        
        Triggered when a dialog is closed, either by user action, JS abort,
or a command below.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
            once: If True, callback will be removed after first execution (register mode only).
        
        Note:
            The behavior depends on the mode:
            - register mode: Adds the callback
            - unregister mode: Removes the callback (once parameter is ignored)
        """
        if self._mode == 'register':
            self._registry.register("FedCm.dialogClosed", callback, once)
        else:  # unregister mode
            self._registry.unregister("FedCm.dialogClosed", callback)

