# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP WebAuthn Domain Events"""

from typing import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import AuthenticatorId
    from .types import Credential

"""Triggered when a credential is added to an authenticator."""
class CredentialAddedEvent(TypedDict):
    authenticatorId: "AuthenticatorId"
    credential: "Credential"



"""Triggered when a credential is deleted, e.g. through
PublicKeyCredential.signalUnknownCredential()."""
class CredentialDeletedEvent(TypedDict):
    authenticatorId: "AuthenticatorId"
    credentialId: "str"



"""Triggered when a credential is updated, e.g. through
PublicKeyCredential.signalCurrentUserDetails()."""
class CredentialUpdatedEvent(TypedDict):
    authenticatorId: "AuthenticatorId"
    credential: "Credential"



"""Triggered when a credential is used in a webauthn assertion."""
class CredentialAssertedEvent(TypedDict):
    authenticatorId: "AuthenticatorId"
    credential: "Credential"
